[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "interactive-unet"
version = "0.2.0"
description = "An interactive segmentation tool for 3D volumetric data."
license = { text = "BSD-2-Clause" }
requires-python = ">=3.11"

dependencies = [
  "nicegui==3.4.1",
  "torch==2.9.1",
  "torchvision==0.24.1",
  "opencv-python==4.12.0.88",
  "tifffile==2026.1.14",
  "segmentation-models-pytorch==0.5.0",
  "scipy==1.16.3",
  "pandas==2.3.3",
  "zarr==3.1.5",
  "tensorstore==0.1.80",
  "numba==0.63.1",
  "joblib==1.5.3",
  "tqdm==4.67.1"
]

[project.scripts]
interactive-unet = "interactive_unet.main:main"

[tool.setuptools.packages.find]
include = ["interactive_unet*"]
